import type { CreateGameResponse, Game, GameView } from "@/lib/game/types";
import { gameRepository } from "@/lib/repositories/InMemoryGameRepository";
import { MockAiCodeGenerator } from "@/lib/services/ai/MockAiCodeGenerator";
import { MockCodeExecutor } from "@/lib/services/code-execution/MockCodeExecutor";
export class GameError extends Error { constructor(message: string, public readonly status: 400 | 404 | 409) { super(message); } }
const aiCodeGenerator = new MockAiCodeGenerator(); const codeExecutor = new MockCodeExecutor();
function requireGame(gameId: unknown): Game { if (typeof gameId !== "string" || !gameId) throw new GameError("gameId is required", 400); const game = gameRepository.get(gameId); if (!game) throw new GameError("Game not found", 404); return game; }
export function createGame(playerNames: unknown): CreateGameResponse { if (!Array.isArray(playerNames) || playerNames.length !== 2 || playerNames.some((name) => typeof name !== "string" || !name.trim())) throw new GameError("Exactly two player names are required", 400); const game = gameRepository.create(playerNames.map((name) => name.trim())); return { gameId: game.id, id: game.id, players: game.players, currentPlayerId: game.currentPlayerId, status: game.status }; }
export async function generateCode(gameId: unknown): Promise<GameView> { const game = requireGame(gameId); const generated = await aiCodeGenerator.generateCode(); Object.assign(game, generated, { lastTestResult: null }); gameRepository.save(game); return toView(game); }
export function deleteLine(gameId: unknown, playerId: unknown, lineIndex: unknown) { const game = requireGame(gameId); if (game.status !== "playing" || game.pendingPlayerId) throw new GameError("Test this turn first", 409); if (playerId !== game.currentPlayerId) throw new GameError("Not your turn", 409); const lines = game.code.split("\n"); if (typeof lineIndex !== "number" || !Number.isInteger(lineIndex) || lineIndex < 0 || lineIndex >= lines.length) throw new GameError("Invalid lineIndex", 400); game.pendingLineWasBlank = lines[lineIndex].trim() === ""; lines.splice(lineIndex, 1); game.code = lines.join("\n"); game.pendingPlayerId = game.currentPlayerId; game.pendingLineIndex = lineIndex; gameRepository.save(game); const nextPlayer = game.players.find((player) => player.id !== game.currentPlayerId); return { gameId: game.id, removedLineIndex: lineIndex, code: game.code, nextPlayerId: nextPlayer?.id }; }
export async function testGame(gameId: unknown) { const game = requireGame(gameId); if (!game.pendingPlayerId) throw new GameError("Delete a line first", 409); const execution = await codeExecutor.execute({ language: game.language, code: game.code, testCode: game.testCode, removedLineWasBlank: game.pendingLineWasBlank }); game.lastTestResult = execution.passed ? "SAFE" : "LOSE"; if (execution.passed) { const nextPlayer = game.players.find((player) => player.id !== game.currentPlayerId); game.currentPlayerId = nextPlayer?.id ?? game.currentPlayerId; } else { game.status = "finished"; game.loserPlayerId = game.pendingPlayerId; } game.pendingPlayerId = undefined; game.pendingLineIndex = undefined; game.pendingLineWasBlank = undefined; gameRepository.save(game); return { result: game.lastTestResult, passed: execution.passed, output: execution.output, nextPlayerId: execution.passed ? game.currentPlayerId : undefined, loserPlayerId: game.loserPlayerId, game: toView(game) }; }
function toView(game: Game): GameView { return { id: game.id, players: game.players, code: game.code, language: game.language, currentPlayerId: game.currentPlayerId, status: game.status, lastTestResult: game.lastTestResult, loserPlayerId: game.loserPlayerId, pendingPlayerId: game.pendingPlayerId, pendingLineIndex: game.pendingLineIndex }; }